In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('readmission.csv')
dataset

encounter_id  patient_nbr             race  gender      age weight  \
0            2278392      8222157        Caucasian  Female   [0-10)      ?   
1             149190     55629189        Caucasian  Female  [10-20)      ?   
2              64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3             500364     82442376        Caucasian    Male  [30-40)      ?   
4              16680     42519267        Caucasian    Male  [40-50)      ?   
...              ...          ...              ...     ...      ...    ...   
101761     443847548    100162476  AfricanAmerican    Male  [70-80)      ?   
101762     443847782     74694222  AfricanAmerican  Female  [80-90)      ?   
101763     443854148     41088789        Caucasian    Male  [70-80)      ?   
101764     443857166     31693671        Caucasian  Female  [80-90)      ?   
101765     443867222    175429310        Caucasian    Male  [70-80)      ?   

        admission_type_id  discharge_disposition_id  admission_source_id  \
0                       6                        25                    1   
1                       1                         1                    7   
2                       1                         1                    7   
3                       1                         1                    7   
4                       1                         1                    7   
...                   ...                       ...                  ...   
101761                  1                         3                    7   
101762                  1                         4                    5   
101763                  1                         1                    7   
101764                  2                         3                    7   
101765                  1                         1                    7   

        time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                      1  ...          No      No                   No   
1                      3  ...          No      Up                   No   
2                      2  ...          No      No                   No   
3                      2  ...          No      Up                   No   
4                      1  ...          No  Steady                   No   
...                  ...  ...         ...     ...                  ...   
101761                 3  ...          No    Down                   No   
101762                 5  ...          No  Steady                   No   
101763                 1  ...          No    Down                   No   
101764                10  ...          No      Up                   No   
101765                 6  ...          No      No                   No   

        glipizide-metformin  glimepiride-pioglitazone  \
0                        No                        No   
1                        No                        No   
2                        No                        No   
3                        No                        No   
4                        No                        No   
...                     ...                       ...   
101761                   No                        No   
101762                   No                        No   
101763                   No                        No   
101764                   No                        No   
101765                   No                        No   

        metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed  \
0                            No                      No      No          No   
1                            No                      No      Ch         Yes   
2                            No                      No      No         Yes   
3                            No                      No      Ch         Yes   
4                            No                      No      Ch         Yes   
...                         ...                     ...     ...         ...   
101761                       No

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.describe()

encounter_id   patient_nbr  admission_type_id  \
count  1.017660e+05  1.017660e+05      101766.000000   
mean   1.652016e+08  5.433040e+07           2.024006   
std    1.026403e+08  3.869636e+07           1.445403   
min    1.252200e+04  1.350000e+02           1.000000   
25%    8.496119e+07  2.341322e+07           1.000000   
50%    1.523890e+08  4.550514e+07           1.000000   
75%    2.302709e+08  8.754595e+07           3.000000   
max    4.438672e+08  1.895026e+08           8.000000   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
count             101766.000000        101766.000000     101766.000000   
mean                   3.715642             5.754437          4.395987   
std                    5.280166             4.064081          2.985108   
min                    1.000000             1.000000          1.000000   
25%                    1.000000             1.000000          2.000000   
50%                    1.000000             7.000000          4.000000   
75%                    4.000000             7.000000          6.000000   
max                   28.000000            25.000000         14.000000   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
count       101766.000000   101766.000000    101766.000000      101766.000000   
mean            43.095641        1.339730        16.021844           0.369357   
std             19.674362        1.705807         8.127566           1.267265   
min              1.000000        0.000000         1.000000           0.000000   
25%             31.000000        0.000000        10.000000           0.000000   
50%             44.000000        1.000000        15.000000           0.000000   
75%             57.000000        2.000000        20.000000           0.000000   
max            132.000000        6.000000        81.000000          42.000000   

       number_emergency  number_inpatient  number_diagnoses  
count     101766.000000     101766.000000     101766.000000  
mean           0.197836          0.635566          7.422607  
std            0.930472          1.262863          1.933600  
min            0.000000          0.000000          1.000000  
25%            0.000000          0.000000          6.000000  
50%            0.000000          0.000000          8.000000  
75%            0.000000          1.000000          9.000000  
max           76.000000         21.000000         16.000000

In [5]:
dataset.corr()

encounter_id  patient_nbr  admission_type_id  \
encounter_id                  1.000000     0.512028          -0.158961   
patient_nbr                   0.512028     1.000000          -0.011128   
admission_type_id            -0.158961    -0.011128           1.000000   
discharge_disposition_id     -0.132876    -0.136814           0.083483   
admission_source_id          -0.112402    -0.032568           0.106654   
time_in_hospital             -0.062221    -0.024092          -0.012500   
num_lab_procedures           -0.026062     0.015946          -0.143713   
num_procedures               -0.014225    -0.015570           0.129888   
num_medications               0.076113     0.020665           0.079535   
number_outpatient             0.103756     0.103379           0.026511   
number_emergency              0.082803     0.062352          -0.019116   
number_inpatient              0.030962     0.012480          -0.038161   
number_diagnoses              0.265149     0.226847          -0.117126   

                          discharge_disposition_id  admission_source_id  \
encounter_id                             -0.132876            -0.112402   
patient_nbr                              -0.136814            -0.032568   
admission_type_id                         0.083483             0.106654   
discharge_disposition_id                  1.000000             0.018193   
admission_source_id                       0.018193             1.000000   
time_in_hospital                          0.162748            -0.006965   
num_lab_procedures                        0.023415             0.048885   
num_procedures                            0.015921            -0.135400   
num_medications                           0.108753            -0.054533   
number_outpatient                        -0.008715             0.027244   
number_emergency                         -0.024471             0.059892   
number_inpatient                          0.020787             0.036314   
number_diagnoses                          0.046891             0.072114   

                          time_in_hospital  num_lab_procedures  \
encounter_id                     -0.062221           -0.026062   
patient_nbr                      -0.024092            0.015946   
admission_type_id                -0.012500           -0.143713   
discharge_disposition_id          0.162748            0.023415   
admission_source_id              -0.006965            0.048885   
time_in_hospital                  1.000000            0.318450   
num_lab_procedures                0.318450            1.000000   
num_procedures                    0.191472            0.058066   
num_medications                   0.466135            0.268161   
number_outpatient                -0.008916           -0.007602   
number_emergency                 -0.009681           -0.002279   
number_inpatient                  0.073623            0.039231   
number_diagnoses                  0.220186            0.152773   

                          num_procedures  num_medications  number_outpatient  \
encounter_id                   -0.014225         0.076113           0.103756   
patient_nbr                    -0.015570         0.020665           0.103379   
admission_type_id               0.129888         0.079535           0.026511   
discharge_disposition_id        0.015921         0.108753          -0.008715   
admission_source_id            -0.135400        -0.054533           0.027244   
time_in_hospital                0.191472         0.466135          -0.008916   
num_lab_procedures              0.058066         0.268161          -0.007602   
num_procedures                  1.000000         0.385767          -0.024819   
num_medications                 0.385767         1.000000           0.045197   
number_outpatient              -0.024819         0.045197           1.000000   
number_emergency               -0.038179         0.013180           0.091459   
number_inpatient               -0.066236         0.06

In [6]:
dataset=dataset.replace('?',np.nan)
dataset

encounter_id  patient_nbr             race  gender      age weight  \
0            2278392      8222157        Caucasian  Female   [0-10)    NaN   
1             149190     55629189        Caucasian  Female  [10-20)    NaN   
2              64410     86047875  AfricanAmerican  Female  [20-30)    NaN   
3             500364     82442376        Caucasian    Male  [30-40)    NaN   
4              16680     42519267        Caucasian    Male  [40-50)    NaN   
...              ...          ...              ...     ...      ...    ...   
101761     443847548    100162476  AfricanAmerican    Male  [70-80)    NaN   
101762     443847782     74694222  AfricanAmerican  Female  [80-90)    NaN   
101763     443854148     41088789        Caucasian    Male  [70-80)    NaN   
101764     443857166     31693671        Caucasian  Female  [80-90)    NaN   
101765     443867222    175429310        Caucasian    Male  [70-80)    NaN   

        admission_type_id  discharge_disposition_id  admission_source_id  \
0                       6                        25                    1   
1                       1                         1                    7   
2                       1                         1                    7   
3                       1                         1                    7   
4                       1                         1                    7   
...                   ...                       ...                  ...   
101761                  1                         3                    7   
101762                  1                         4                    5   
101763                  1                         1                    7   
101764                  2                         3                    7   
101765                  1                         1                    7   

        time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                      1  ...          No      No                   No   
1                      3  ...          No      Up                   No   
2                      2  ...          No      No                   No   
3                      2  ...          No      Up                   No   
4                      1  ...          No  Steady                   No   
...                  ...  ...         ...     ...                  ...   
101761                 3  ...          No    Down                   No   
101762                 5  ...          No  Steady                   No   
101763                 1  ...          No    Down                   No   
101764                10  ...          No      Up                   No   
101765                 6  ...          No      No                   No   

        glipizide-metformin  glimepiride-pioglitazone  \
0                        No                        No   
1                        No                        No   
2                        No                        No   
3                        No                        No   
4                        No                        No   
...                     ...                       ...   
101761                   No                        No   
101762                   No                        No   
101763                   No                        No   
101764                   No                        No   
101765                   No                        No   

        metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed  \
0                            No                      No      No          No   
1                            No                      No      Ch         Yes   
2                            No                      No      No         Yes   
3                            No                      No      Ch         Yes   
4                            No                      No      Ch         Yes   
...                         ...                     ...     ...         ...   
101761                       No

In [7]:
dataset.isnull().any()

encounter_id                False
patient_nbr                 False
race                         True
gender                      False
age                         False
weight                       True
admission_type_id           False
discharge_disposition_id    False
admission_source_id         False
time_in_hospital            False
payer_code                   True
medical_specialty            True
num_lab_procedures          False
num_procedures              False
num_medications             False
number_outpatient           False
number_emergency            False
number_inpatient            False
diag_1                       True
diag_2                       True
diag_3                       True
number_diagnoses            False
max_glu_serum               False
A1Cresult                   False
metformin                   False
repaglinide                 False
nateglinide                 False
chlorpropamide              False
glimepiride                 False
acetohexamide 

In [8]:
dataset.drop(['medical_specialty','weight','encounter_id','patient_nbr','examide','citoglipton','payer_code','diag_1','diag_2','diag_3','admission_type_id','discharge_disposition_id','admission_source_id','num_lab_procedures','num_procedures','num_medications','acetohexamide','tolbutamide','acarbose','miglitol','troglitazone','tolazamide','glyburide-metformin','glipizide-metformin','glimepiride-pioglitazone','metformin-rosiglitazone','metformin-pioglitazone'],axis=1,inplace=True)
dataset

race  gender      age  time_in_hospital  number_outpatient  \
0             Caucasian  Female   [0-10)                 1                  0   
1             Caucasian  Female  [10-20)                 3                  0   
2       AfricanAmerican  Female  [20-30)                 2                  2   
3             Caucasian    Male  [30-40)                 2                  0   
4             Caucasian    Male  [40-50)                 1                  0   
...                 ...     ...      ...               ...                ...   
101761  AfricanAmerican    Male  [70-80)                 3                  0   
101762  AfricanAmerican  Female  [80-90)                 5                  0   
101763        Caucasian    Male  [70-80)                 1                  1   
101764        Caucasian  Female  [80-90)                10                  0   
101765        Caucasian    Male  [70-80)                 6                  0   

        number_emergency  number_inpatient  number_diagnoses max_glu_serum  \
0                      0                 0                 1          None   
1                      0                 0                 9          None   
2                      0                 1                 6          None   
3                      0                 0                 7          None   
4                      0                 0                 5          None   
...                  ...               ...               ...           ...   
101761                 0                 0                 9          None   
101762                 0                 1                 9          None   
101763                 0                 0                13          None   
101764                 0                 1                 9          None   
101765                 0                 0                 9          None   

       A1Cresult  ... chlorpropamide glimepiride glipizide glyburide  \
0           None  ...             No          No        No        No   
1           None  ...             No          No        No        No   
2           None  ...             No          No    Steady        No   
3           None  ...             No          No        No        No   
4           None  ...             No          No    Steady        No   
...          ...  ...            ...         ...       ...       ...   
101761        >8  ...             No          No        No        No   
101762      None  ...             No          No        No        No   
101763      None  ...             No          No        No        No   
101764      None  ...             No          No    Steady        No   
101765      None  ...             No          No        No        No   

       pioglitazone rosiglitazone insulin change diabetesMed readmitted  
0                No            No      No     No          No         NO  
1                No            No      Up     Ch         Yes        >30  
2                No            No      No     No         Yes         NO  
3                No            No      Up     Ch         Yes         NO  
4                No            No  Steady     Ch         Yes         NO  
...             ...           ...     ...    ...         ...        ...  
101761           No            No    Down     Ch         Yes        >30  
101762           No            No  Steady     No         Yes         NO  
101763           No            No    Down     Ch         Yes         NO  
101764       Steady            No      Up     Ch         Yes         NO  
101765           No            No      No     No          No         NO  

[101766 rows x 23 columns]

In [9]:
dataset['race']=dataset['race'].fillna(value='UNK')
dataset

race  gender      age  time_in_hospital  number_outpatient  \
0             Caucasian  Female   [0-10)                 1                  0   
1             Caucasian  Female  [10-20)                 3                  0   
2       AfricanAmerican  Female  [20-30)                 2                  2   
3             Caucasian    Male  [30-40)                 2                  0   
4             Caucasian    Male  [40-50)                 1                  0   
...                 ...     ...      ...               ...                ...   
101761  AfricanAmerican    Male  [70-80)                 3                  0   
101762  AfricanAmerican  Female  [80-90)                 5                  0   
101763        Caucasian    Male  [70-80)                 1                  1   
101764        Caucasian  Female  [80-90)                10                  0   
101765        Caucasian    Male  [70-80)                 6                  0   

        number_emergency  number_inpatient  number_diagnoses max_glu_serum  \
0                      0                 0                 1          None   
1                      0                 0                 9          None   
2                      0                 1                 6          None   
3                      0                 0                 7          None   
4                      0                 0                 5          None   
...                  ...               ...               ...           ...   
101761                 0                 0                 9          None   
101762                 0                 1                 9          None   
101763                 0                 0                13          None   
101764                 0                 1                 9          None   
101765                 0                 0                 9          None   

       A1Cresult  ... chlorpropamide glimepiride glipizide glyburide  \
0           None  ...             No          No        No        No   
1           None  ...             No          No        No        No   
2           None  ...             No          No    Steady        No   
3           None  ...             No          No        No        No   
4           None  ...             No          No    Steady        No   
...          ...  ...            ...         ...       ...       ...   
101761        >8  ...             No          No        No        No   
101762      None  ...             No          No        No        No   
101763      None  ...             No          No        No        No   
101764      None  ...             No          No    Steady        No   
101765      None  ...             No          No        No        No   

       pioglitazone rosiglitazone insulin change diabetesMed readmitted  
0                No            No      No     No          No         NO  
1                No            No      Up     Ch         Yes        >30  
2                No            No      No     No         Yes         NO  
3                No            No      Up     Ch         Yes         NO  
4                No            No  Steady     Ch         Yes         NO  
...             ...           ...     ...    ...         ...        ...  
101761           No            No    Down     Ch         Yes        >30  
101762           No            No  Steady     No         Yes         NO  
101763           No            No    Down     Ch         Yes         NO  
101764       Steady            No      Up     Ch         Yes         NO  
101765           No            No      No     No          No         NO  

[101766 rows x 23 columns]

In [10]:
dataset = dataset[~dataset.gender.str.contains("Unknown")]




In [11]:
dataset['readmitted'] = dataset['readmitted'].replace(to_replace ="<30", 
                 value ="yes") 
dataset['readmitted']

C:\Users\chinni\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0          NO
1         >30
2          NO
3          NO
4          NO
         ... 
101761    >30
101762     NO
101763     NO
101764     NO
101765     NO
Name: readmitted, Length: 101763, dtype: object

In [12]:
dataset['readmitted'] = dataset['readmitted'].replace(to_replace =">30", 
                 value ="yes") 
dataset['readmitted']

C:\Users\chinni\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0          NO
1         yes
2          NO
3          NO
4          NO
         ... 
101761    yes
101762     NO
101763     NO
101764     NO
101765     NO
Name: readmitted, Length: 101763, dtype: object

In [13]:
dataset.isnull().any()

race                 False
gender               False
age                  False
time_in_hospital     False
number_outpatient    False
number_emergency     False
number_inpatient     False
number_diagnoses     False
max_glu_serum        False
A1Cresult            False
metformin            False
repaglinide          False
nateglinide          False
chlorpropamide       False
glimepiride          False
glipizide            False
glyburide            False
pioglitazone         False
rosiglitazone        False
insulin              False
change               False
diabetesMed          False
readmitted           False
dtype: bool

In [14]:
x=dataset.iloc[:,0:22].values
x

array([['Caucasian', 'Female', '[0-10)', ..., 'No', 'No', 'No'],
       ['Caucasian', 'Female', '[10-20)', ..., 'Up', 'Ch', 'Yes'],
       ['AfricanAmerican', 'Female', '[20-30)', ..., 'No', 'No', 'Yes'],
       ...,
       ['Caucasian', 'Male', '[70-80)', ..., 'Down', 'Ch', 'Yes'],
       ['Caucasian', 'Female', '[80-90)', ..., 'Up', 'Ch', 'Yes'],
       ['Caucasian', 'Male', '[70-80)', ..., 'No', 'No', 'No']],
      dtype=object)

In [15]:
x.shape

(101763, 22)

In [16]:
y=dataset.iloc[:,22:].values
y


array([['NO'],
       ['yes'],
       ['NO'],
       ...,
       ['NO'],
       ['NO'],
       ['NO']], dtype=object)

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [18]:
ct=ColumnTransformer([('on',OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 0.0, 1.0, ..., 'No', 'No', 'No'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 0.0, 1.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'No']], dtype=object)

In [19]:
x=x[:,1:]
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:,5] = lb.fit_transform(x[:,5])
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [21]:
ct=ColumnTransformer([('on',OneHotEncoder(),[6])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 0.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [22]:
x=x[:,1:]
x

array([[0.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 0.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [23]:
ct=ColumnTransformer([('on',OneHotEncoder(),[20])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 0.0, 1.0, ..., 'No', 'No', 'No'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 0.0, 1.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'No']], dtype=object)

In [24]:
x=x[:,1:]
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [25]:
ct=ColumnTransformer([('on',OneHotEncoder(),[23])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 0.0, 1.0, ..., 'No', 'No', 'No'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 0.0, 1.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'No']], dtype=object)

In [26]:
x=x[:,1:]
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [27]:
ct=ColumnTransformer([('on',OneHotEncoder(),[26])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 0.0, 1.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [28]:
x = x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [29]:
ct=ColumnTransformer([('on',OneHotEncoder(),[29])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [30]:
x = x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [31]:
ct=ColumnTransformer([('on',OneHotEncoder(),[32])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [32]:
x = x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [33]:
ct=ColumnTransformer([('on',OneHotEncoder(),[36])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [34]:
x = x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [35]:
ct=ColumnTransformer([('on',OneHotEncoder(),[39])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 'No', 'No', 'No'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'No', 'No', 'Yes'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 0.0, 1.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [36]:
x = x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 'No', 'No', 'No'],
       [1.0, 0.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'No', 'No', 'Yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'Down', 'Ch', 'Yes'],
       [0.0, 1.0, 0.0, ..., 'Up', 'Ch', 'Yes'],
       [1.0, 0.0, 0.0, ..., 'No', 'No', 'No']], dtype=object)

In [37]:
ct=ColumnTransformer([('on',OneHotEncoder(),[42])],remainder="passthrough")
x=ct.fit_transform(x)
x = x[:,1:]
x[0,0:]

array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0, 1,
       0, 0, 0, 1, 'No', 'No', 'No', 'No', 'No', 'No'], dtype=object)

In [38]:
ct=ColumnTransformer([('on',OneHotEncoder(),[45])],remainder="passthrough")
x=ct.fit_transform(x)
x = x[:,1:]


In [39]:
ct=ColumnTransformer([('on',OneHotEncoder(),[47])],remainder="passthrough")
x=ct.fit_transform(x)
x = x[:,1:]


In [40]:
ct=ColumnTransformer([('on',OneHotEncoder(),[50])],remainder="passthrough")
x=ct.fit_transform(x)
x = x[:,1:]
x[0,0:]

array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0, 1, 0, 0, 0, 1, 'No',
       'No', 'No'], dtype=object)

In [41]:
ct=ColumnTransformer([('on',OneHotEncoder(),[53])],remainder="passthrough")
x=ct.fit_transform(x)
x = x[:,1:]
x[0,0:]

array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0, 1, 0, 0,
       0, 1, 'No', 'No'], dtype=object)

In [42]:

x[:,56]=lb.fit_transform(x[:,56])

In [43]:

x[:,57]=lb.fit_transform(x[:,57])

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[ 1.07135661, -0.65956037, -0.35371167, ..., -3.32165625,
         0.92657927, -1.82988374],
       [-0.93339603, -0.65956037,  2.82716147, ...,  0.81577228,
        -1.07923847,  0.54648281],
       [ 1.07135661, -0.65956037, -0.35371167, ..., -0.73576342,
         0.92657927,  0.54648281],
       ...,
       [-0.93339603, -0.65956037, -0.35371167, ...,  2.88448655,
        -1.07923847,  0.54648281],
       [-0.93339603, -0.65956037,  2.82716147, ...,  0.81577228,
        -1.07923847,  0.54648281],
       [ 1.07135661, -0.65956037, -0.35371167, ...,  0.81577228,
         0.92657927, -1.82988374]])

In [45]:
from joblib import dump
dump(sc,"scalar.save")

['scalar.save']

In [46]:

y=lb.fit_transform(y)
y

C:\Users\chinni\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, ..., 0, 0, 0])

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [49]:
x_train

array([[ 1.07135661, -0.65956037, -0.35371167, ...,  0.29859372,
         0.92657927,  0.54648281],
       [ 1.07135661, -0.65956037, -0.35371167, ...,  0.81577228,
         0.92657927, -1.82988374],
       [ 1.07135661, -0.65956037, -0.35371167, ...,  0.81577228,
         0.92657927, -1.82988374],
       ...,
       [-0.93339603,  1.51616144, -0.35371167, ...,  0.81577228,
         0.92657927,  0.54648281],
       [ 1.07135661, -0.65956037, -0.35371167, ...,  0.81577228,
         0.92657927,  0.54648281],
       [-0.93339603,  1.51616144, -0.35371167, ...,  0.81577228,
         0.92657927,  0.54648281]])

In [50]:
x_train.shape

(81410, 58)

In [51]:
y_train.shape

(81410,)

In [52]:
x_test

array([[-0.93339603,  1.51616144, -0.35371167, ...,  0.81577228,
        -1.07923847,  0.54648281],
       [-0.93339603, -0.65956037, -0.35371167, ..., -0.73576342,
        -1.07923847,  0.54648281],
       [ 1.07135661, -0.65956037, -0.35371167, ..., -0.73576342,
         0.92657927,  0.54648281],
       ...,
       [ 1.07135661, -0.65956037, -0.35371167, ...,  0.81577228,
         0.92657927, -1.82988374],
       [-0.93339603,  1.51616144, -0.35371167, ...,  0.81577228,
        -1.07923847,  0.54648281],
       [ 1.07135661, -0.65956037, -0.35371167, ...,  0.81577228,
         0.92657927,  0.54648281]])

In [53]:
y_test

array([0, 1, 0, ..., 1, 1, 1])

In [54]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
pipe = Pipeline([
    ('rescale', StandardScaler()),
    ('classifier', SVC(kernel = 'rbf'))
])

In [55]:
pipe.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('rescale',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('classifier',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='scale', kernel='rbf', max_iter=-1,
                     probability=False, random_state=None, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [56]:
y_pred = pipe.predict(x_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6193190193091928